language: cpp
script: ./test.sh
os: linux
compiler:
  - gcc
matrix:
  include:    
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7

before_install:
    - pip install --user cpp-coveralls

after_success:
  - pip install gcovr
  - gcovr -r . --xml-pretty -o cobertura.xml
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r cobertura.xml